apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
  name: pyspark-pi
  labels:
    app: hellosparkpi
  namespace: mel-spark-gcp
spec:
  type: Python
  pythonVersion: '2'
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
    type: OnFailure
  mode: cluster
  mainApplicationFile: 'https://melbdcsa.blob.core.windows.net/sparkpy/sample_hello_pyspark.py'
  image: 'gcr.io/spark-operator/spark-py:v2.4.0'
  sparkVersion: 2.4.0
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  imagePullPolicy: Always
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
  